"""Generate models/_generated.py from the JSON schema via datamodel-code-generator."""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SCHEMA_PATH = _ROOT / "schemas" / "model-config.schema.json"
_OUTPUT_PATH = _ROOT / "models" / "_generated.py"

_HEADER = '''\
# DO NOT EDIT — auto-generated from schemas/model-config.schema.json
# Regenerate with: agents generate-config
#
# generated by datamodel-code-generator:
#   filename:  model-config.schema.json
'''

# Rename generated classes to match the public API in models/config.py
_RENAMES: list[tuple[str, str]] = [
    ("class ModalLLMModelConfiguration(", "class ModelConfigBase("),
    ("class Model(", "class ModelSection("),
    ("class Engine(", "class EngineConfig("),
    ("class Type(StrEnum):", "class EngineType(StrEnum):"),
    ("class GPU(", "class GpuConfig("),
    ("class Scaling(", "class ScalingConfig("),
    ("class VLLMArguments(", "class VllmArgsConfig("),
    ("class Image(", "class ImageConfig("),
    ("class Volumes(", "class VolumesConfig("),
    ("class Auth(", "class AuthConfig("),
    ("model: Model", "model: ModelSection"),
    ("engine: Engine", "engine: EngineConfig"),
    ("gpu: GPU", "gpu: GpuConfig"),
    ("scaling: Scaling", "scaling: ScalingConfig"),
    ("vllm_args: VLLMArguments", "vllm_args: VllmArgsConfig"),
    ("image: Image", "image: ImageConfig"),
    ("volumes: Volumes", "volumes: VolumesConfig"),
    ("auth: Auth", "auth: AuthConfig"),
    ("type: Type | None", "type: EngineType | None"),
]

# Remove oneOf GPU types (Type1 enum / Type2 RootModel) — use str | list[str] instead
_GPU_TYPE_BLOCK = re.compile(
    r"\nclass Type1\(StrEnum\):.*?"
    r"\n\nclass GpuConfig\(BaseModel\):",
    re.DOTALL,
)

_GPU_TYPE_FIELD = """\
    type: str | list[str] = Field(
        default='H200',
        description='Modal GPU type or fallback list. Accepts a single GPU type string or an array for fallback scheduling. Modal tries each GPU in order and falls back to the next if unavailable. See https://modal.com/docs/guide/gpu for details and https://modal.com/pricing for costs.',
        examples=['H200', 'A100-80GB', ['H100', 'A100-80GB'], ['B200', 'H200:2']],
    )"""

_NESTED_DEFAULTS = [
    ("engine: EngineConfig | None = None", "engine: EngineConfig = Field(default_factory=EngineConfig)"),
    ("gpu: GpuConfig | None = None", "gpu: GpuConfig = Field(default_factory=GpuConfig)"),
    ("scaling: ScalingConfig | None = None", "scaling: ScalingConfig = Field(default_factory=ScalingConfig)"),
    ("vllm_args: VllmArgsConfig | None = None", "vllm_args: VllmArgsConfig = Field(default_factory=VllmArgsConfig)"),
    ("image: ImageConfig | None = None", "image: ImageConfig = Field(default_factory=ImageConfig)"),
    ("volumes: VolumesConfig | None = None", "volumes: VolumesConfig = Field(default_factory=VolumesConfig)"),
]


def _run_datamodel_codegen(out_path: Path) -> None:
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            str(_SCHEMA_PATH),
            "--input-file-type",
            "jsonschema",
            "--output",
            str(out_path),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.11",
            "--use-union-operator",
            "--field-constraints",
            "--use-title-as-name",
            "--disable-timestamp",
        ],
        check=True,
        cwd=_ROOT,
    )


def _post_process(source: str) -> str:
    for old, new in _RENAMES:
        source = source.replace(old, new)

    source = _GPU_TYPE_BLOCK.sub(f"\n\nclass GpuConfig(BaseModel):", source)

    # Replace the broken generated gpu.type field with a simple union
    source = re.sub(
        r"    type: EngineType \| Type2 \| None = Field\([^)]*\)\n"
        r"        [^\n]*\n"
        r"        [^\n]*\n"
        r"        validate_default=True,\n"
        r"    \)",
        _GPU_TYPE_FIELD + "\n",
        source,
        count=1,
    )
    # Fallback if pattern differs (Type1 still present)
    source = re.sub(
        r"    type: Type1 \| Type2 \| None = Field\([\s\S]*?validate_default=True,\n    \)",
        _GPU_TYPE_FIELD + "\n",
        source,
        count=1,
    )

    for old, new in _NESTED_DEFAULTS:
        source = source.replace(old, new)

    # Strip datamodel-codegen auto header (we use our own)
    source = re.sub(
        r"# generated by datamodel-codegen:.*?\n\n",
        "",
        source,
        count=1,
        flags=re.DOTALL,
    )

    source = source.replace("from pydantic import BaseModel, ConfigDict, Field, RootModel\n",
                            "from pydantic import BaseModel, ConfigDict, Field\n")

    return _HEADER + source.lstrip()


def generate_config(*, check: bool = False) -> bool:
    """Generate models/_generated.py. Returns True if output changed."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as tmp:
        tmp_path = Path(tmp.name)

    try:
        _run_datamodel_codegen(tmp_path)
        new_content = _post_process(tmp_path.read_text())
    finally:
        tmp_path.unlink(missing_ok=True)

    if _OUTPUT_PATH.exists():
        old_content = _OUTPUT_PATH.read_text()
        if old_content == new_content:
            return False
    else:
        old_content = None

    if check:
        return old_content != new_content

    _OUTPUT_PATH.write_text(new_content)
    return True


def main() -> None:
    check = "--check" in sys.argv
    changed = generate_config(check=check)

    if check:
        if changed:
            print(
                "models/_generated.py is out of date. "
                "Run 'agents generate-config' to update.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("models/_generated.py is up to date.")
    elif changed:
        print(f"Updated {_OUTPUT_PATH.relative_to(_ROOT)}")
    else:
        print("models/_generated.py is already up to date. No changes made.")


if __name__ == "__main__":
    main()
