# DO NOT EDIT — auto-generated from schemas/model-config.schema.json
# Regenerate with: agents generate-config
#
# generated by datamodel-code-generator:
#   filename:  model-config.schema.json
from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class AuthConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_name: str = Field(
        ...,
        description='Name of the Modal Secret that holds the API token. The secret must contain an AUTH_TOKEN key (see https://modal.com/docs/guide/webhooks#token-based-authentication). vLLM is started with --api-key so clients must send Authorization: Bearer <token> on /v1 requests. Create the secret with: modal secret create <token_name> AUTH_TOKEN=<your-token>. Alternatively pass at deploy or run time: agents deploy <config> -t <token_name>',
        examples=['my-llm-auth', 'gemma4-26b-auth'],
    )


class ModelSection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Hugging Face repository ID for the model weights. This is the only required field in the entire configuration.',
        examples=[
            'google/gemma-4-26B-A4B-it',
            'meta-llama/Llama-3.1-8B-Instruct',
            'Qwen/Qwen3-Coder-Next-FP8',
            'deepseek-ai/DeepSeek-R1',
        ],
    )
    revision: str | None = Field(
        None,
        description='Git commit hash to pin model weights to a specific version. Prevents surprise weight updates when the Hugging Face repo is updated. Find the latest commit hash on the model page under Files > Commits. If omitted, always pulls the latest revision.',
        examples=['47b6801b24d15ff9bcd8c96dfaea0be9ed3a0301'],
        pattern='^[0-9a-f]{7,40}$',
    )
    served_name: str | None = Field(
        'llm',
        description="The model name that clients send in the OpenAI API 'model' field when making requests. Using a consistent short name like 'llm' allows swapping the underlying model without changing client code.",
        examples=['llm', 'gpt-4', 'claude'],
    )


class EngineType(StrEnum):
    vllm = 'vllm'


class EngineConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: EngineType | None = Field(
        'vllm',
        description="Serving engine type. Currently only 'vllm' is supported. Future options may include 'sglang'.",
    )
    version: str | None = Field(
        '0.19.0',
        description='Version of the serving engine (vLLM) to install via pip in the container image. Pin to a specific version for reproducible deployments.',
        examples=['0.19.0', '0.18.2', '0.20.0'],
        pattern='^\\d+\\.\\d+(\\.\\d+)?(\\.(dev|post|rc)\\d+)?$',
    )
    extra_pip: list[str] | None = Field(
        [],
        description='Additional pip packages installed alongside the serving engine. Use for model-specific dependencies that are not bundled with vLLM (e.g. newer transformers versions, custom tokenizers).',
        examples=[['transformers==5.5.0'], ['flash-attn>=2.5.0']],
    )



class GpuConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str | list[str] = Field(
        default='H200',
        description='Modal GPU type or fallback list. Accepts a single GPU type string or an array for fallback scheduling. Modal tries each GPU in order and falls back to the next if unavailable. See https://modal.com/docs/guide/gpu for details and https://modal.com/pricing for costs.',
        examples=['H200', 'A100-80GB', ['H100', 'A100-80GB'], ['B200', 'H200:2']],
    )

    count: int | None = Field(
        1,
        description="Number of GPUs per replica. Only applies when 'gpu.type' is a single string — ignored when 'gpu.type' is a fallback array (use the ':N' suffix per entry instead). Use >1 for tensor parallelism on large models. B200, H200, H100, A100, L4, T4, and L40S support up to 8 GPUs (up to 1,536 GB GPU RAM). A10 supports up to 4 GPUs (up to 96 GB GPU RAM). Note: requesting more than 2 GPUs usually results in larger wait times.",
        ge=1,
        le=8,
    )


class ScalingConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scaledown_window_minutes: int | None = Field(
        15,
        description='Minutes a replica stays alive with no incoming requests before scaling to zero. Lower values save cost but increase cold start frequency. Set to 0 for immediate scale-down after the last request completes.',
        examples=[1, 5, 15, 30],
        ge=0,
    )
    timeout_minutes: int | None = Field(
        10,
        description='Container startup timeout in minutes. Modal will kill the container if it does not become healthy within this window. Increase for very large models that take longer to load weights into GPU memory.',
        examples=[10, 15, 20, 30],
        ge=1,
    )
    max_concurrent_inputs: int | None = Field(
        100,
        description='Maximum number of simultaneous requests a single replica will accept. Tune based on GPU memory and model size — larger models or longer contexts may need a lower value to avoid OOM errors.',
        examples=[10, 50, 100, 200],
        ge=1,
    )
    fast_boot: bool | None = Field(
        False,
        description='When true, skips torch compilation during startup for faster cold starts at the cost of lower throughput. Set to true during development/testing and false in production for best inference performance.',
    )


class VllmArgsConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    async_scheduling: bool | None = Field(
        True,
        description="Enable vLLM's async scheduling for better throughput under concurrent load. Adds '--disable-async-output-proc' when set to false.",
    )
    extra_args: list[str] | None = Field(
        [],
        description="Arbitrary CLI flags appended verbatim to the 'vllm serve' command. Each list element is one shell token — flags and their values must be separate entries. See https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html for all available flags.",
        examples=[
            ['--max-model-len', '8192'],
            ['--enable-auto-tool-choice', '--tool-call-parser', 'hermes'],
            ['--trust-remote-code'],
            ['--gpu-memory-utilization', '0.9'],
            ['--enable-prefix-caching'],
            ['--enable-expert-parallel'],
            ['--limit-mm-per-prompt', '{"image": 0, "video": 0, "audio": 0}'],
        ],
    )


class ImageConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base: str | None = Field(
        'nvidia/cuda:12.9.0-devel-ubuntu22.04',
        description='Base Docker image for the container. Must include CUDA drivers compatible with your GPU and vLLM version. See https://hub.docker.com/r/nvidia/cuda/tags for available NVIDIA CUDA images.',
        examples=[
            'nvidia/cuda:12.9.0-devel-ubuntu22.04',
            'nvidia/cuda:12.4.1-devel-ubuntu22.04',
            'nvidia/cuda:12.1.0-devel-ubuntu22.04',
        ],
    )
    python: str | None = Field(
        '3.12',
        description='Python version installed in the container by Modal. Must be compatible with the chosen vLLM version.',
        examples=['3.11', '3.12', '3.13'],
        pattern='^3\\.\\d{1,2}$',
    )
    env: dict[str, str] | None = Field(
        {},
        description='Environment variables baked into the container image at build time. Values must be strings. Use for tuning runtime behavior of vLLM, CUDA, or model-specific settings.',
        examples=[
            {'HF_XET_HIGH_PERFORMANCE': '1'},
            {'VLLM_USE_DEEP_GEMM': '1', 'CUDA_VISIBLE_DEVICES': '0,1'},
        ],
    )


class VolumesConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hf_cache: str | None = Field(
        'huggingface-cache',
        description="Modal Volume name for the Hugging Face model weight cache. Models sharing a volume name share cached weights, saving disk space and download time. Use a unique name (e.g. 'huggingface-cache-my-model') to isolate a model's cache from others.",
        examples=['huggingface-cache', 'huggingface-cache-llama'],
    )
    vllm_cache: str | None = Field(
        'vllm-cache',
        description="Modal Volume name for vLLM's JIT compilation cache. Caches compiled CUDA kernels to speed up warm starts. Use a unique name to isolate if different models use incompatible kernel configurations.",
        examples=['vllm-cache', 'vllm-cache-llama'],
    )


class ModelConfigBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    app_name: str | None = Field(
        None,
        description="Modal app name used to identify this deployment. If omitted, defaults to a slug derived from model.name (e.g. 'google/gemma-4-26B-A4B-it' becomes 'gemma-4-26b-a4b-it'). Must be unique across your Modal workspace if deploying multiple models simultaneously.",
        examples=['gemma4-26b', 'llama-3.1-8b-instruct', 'qwen3-coder-next'],
        pattern='^[a-z0-9][a-z0-9._-]*$',
    )
    model: ModelSection
    engine: EngineConfig = Field(default_factory=EngineConfig)
    gpu: GpuConfig = Field(default_factory=GpuConfig)
    scaling: ScalingConfig = Field(default_factory=ScalingConfig)
    vllm_args: VllmArgsConfig = Field(default_factory=VllmArgsConfig)
    image: ImageConfig = Field(default_factory=ImageConfig)
    volumes: VolumesConfig = Field(default_factory=VolumesConfig)
    auth: AuthConfig | None = None
